export interface Product {
  id: string
  slug: string
  name: string
  price: number
  img: string
  imgLg: string
  droppingFirst: boolean
  sizes: string[]
  description: string
  details: string[]
  collection: string
}

export const FITNESS_PRODUCTS: Product[] = [
  {
    id: 'f_cap_black',
    slug: 'rope-cap',
    name: 'Rope Cap',
    price: 44,
    img: '/images/f_cap_black.png',
    imgLg: '/images/f_cap_black.png',
    droppingFirst: true,
    sizes: ['One Size'],
    description: 'The Dog House Fitness rope cap. Performance fabric, curved brim, woven rope detail, and the DHF patch front and center. Built to wear to the gym, the field, or anywhere the pack runs.',
    details: [
      'Embroidered DHF patch — 2.5" circular',
      'Performance polyester shell',
      'Perforated side panels for breathability',
      'Rope brim detail',
      'Adjustable snapback closure',
      'Dog Days — Drop 001',
    ],
    collection: 'Dog Days — Drop 001',
  },
  {
    id: 'f_cap_camo',
    slug: 'camo-cap',
    name: 'Camo Cap',
    price: 44,
    img: '/images/f_cap_camo.png',
    imgLg: '/images/f_cap_camo.png',
    droppingFirst: true,
    sizes: ['One Size'],
    description: 'Same DHF patch, same build — wrapped in dye-sublimated desert camo. For the ones who move a little different.',
    details: [
      'Dye sublimated full-body camo print',
      'Embroidered DHF patch — 2.5" circular',
      'Perforated side panels',
      'Rope brim detail',
      'Adjustable snapback closure',
      'Dog Days — Drop 001',
    ],
    collection: 'Dog Days — Drop 001',
  },
  {
    id: 'f_tee',
    slug: 'dog-days-tee',
    name: 'Dog Days Tee',
    price: 44,
    img: '/images/f_tee.png',
    imgLg: '/images/f_tee_lg.png',
    droppingFirst: false,
    sizes: ['L', 'XL'],
    description: 'Heavyweight 240-280 GSM, 100% cotton, garment dyed black. Oversized boxy fit with dropped shoulders. "DOG HOUSE" silicone heat transfer on the left chest, full "Dog Days" back graphic in DTG/puff ink with a vintage washed finish. Woven neck label inside.',
    details: [
      '240–280 GSM heavyweight 100% cotton',
      'Oversized / boxy fit — dropped shoulders',
      'Garment dyed black — pre-shrunk',
      'Front: silicone heat transfer left chest',
      'Back: Dog Days full graphic — DTG / puff ink vintage distressed',
      'Woven Dog House Fitness neck label',
      'Tape shoulder to shoulder — double needle hem',
      'Dog Days — Drop 001 — Limited',
    ],
    collection: 'Dog Days — Drop 001',
  },
  {
    id: 'f_zip',
    slug: 'dog-days-zip-hoodie',
    name: 'Dog Days Zip Hoodie',
    price: 78,
    img: '/images/f_zip.png',
    imgLg: '/images/f_zip_lg.png',
    droppingFirst: false,
    sizes: ['L', 'XL'],
    description: 'Heavyweight 450-500 GSM, 100% cotton fleece, garment dyed black. Oversized boxy fit with drop shoulders. "DOG HOUSE" silicone heat transfer on the left chest. Full "Dog Days" back graphic shoulder to shoulder in DTG/puff ink vintage finish. Heavy duty YKK zipper. Woven Dog House Fitness neck label inside.',
    details: [
      '450–500 GSM heavyweight 100% cotton fleece',
      'Oversized / boxy fit — drop shoulder',
      'Garment dyed black — pre-shrunk',
      'Front: silicone heat transfer left chest',
      'Back: Dog Days full graphic — DTG / puff ink vintage distressed',
      'Heavy duty YKK zipper',
      'Double layer hood — kangaroo pockets',
      'Thick ribbed cuffs & waistband — double needle stitch',
      'Woven Dog House Fitness neck label',
      'Dog Days — Drop 001 — Limited',
    ],
    collection: 'Dog Days — Drop 001',
  },
  {
    id: 'f_sweat',
    slug: 'joggers',
    name: 'Joggers',
    price: 64,
    img: '/images/f_sweat.png',
    imgLg: '/images/f_sweat_lg.png',
    droppingFirst: false,
    sizes: ['L', 'XL'],
    description: 'Heavyweight 450-500 GSM, 100% cotton fleece. Oversized relaxed fit with elastic waistband and drawcord. "DOG HOUSE" raised silicone rubber heat transfer on the left hip — matte black finish, raised 3D texture. Deep side pockets, single back pocket, ribbed cuffs.',
    details: [
      '450–500 GSM heavyweight 100% cotton fleece',
      'Oversized / relaxed fit',
      'Elastic waistband with drawcord',
      'Left hip: raised silicone / rubber heat press — matte black',
      'Deep side pockets — single back pocket',
      'Ribbed cuffs',
      'Durable — wash resistant — raised 3D texture',
      'Dog Days — Drop 001 — Limited',
    ],
    collection: 'Dog Days — Drop 001',
  },
  {
    id: 'f_tank',
    slug: 'mens-tank-top',
    name: "Men's Tank Top",
    price: 30,
    img: '/images/f_tank.png',
    imgLg: '/images/f_tank_lg.png',
    droppingFirst: false,
    sizes: ['L', 'XL'],
    description: 'Premium ribbed 92% cotton / 8% spandex. Tight athletic fit that contours to the chest, shoulders, and arms. High armholes. Garment dyed black. Embroidered DHF logo on the back neck. Size up if you prefer a looser fit.',
    details: [
      '92% cotton / 8% spandex — premium ribbed',
      'Tight athletic fit — contours to body',
      'High armholes',
      'Garment dyed black — pre-shrunk',
      'Back neck: embroidered DHF logo',
      'Ribbed stretch fabric — double needle hem',
      'Woven neck label',
      'Size up for a looser fit',
      'Dog Days — Drop 001',
    ],
    collection: 'Dog Days — Drop 001',
  },
  {
    id: 'f_beanie',
    slug: 'dhf-beanie',
    name: 'DHF Beanie',
    price: 23,
    img: '/images/f_beanie.png',
    imgLg: '/images/f_beanie_lg.png',
    droppingFirst: false,
    sizes: ['One Size'],
    description: '100% soft-touch acrylic, 1x1 rib knit, 12 gauge midweight. Double layer with 3" cuff. Embroidered DHF patch with merrow border on the cuff. Interior label reads "Dog House Fitness / Built Different." Available in Black, Charcoal, and Bone.',
    details: [
      '100% soft-touch acrylic — 1x1 rib knit',
      '12 gauge — midweight — double layer',
      '3" cuff — linked crown — 4 top seams',
      '2.5" embroidered DHF patch — merrow border — sewn on',
      'Stretch fit — retains shape — premium finish',
      'Interior label: Dog House Fitness / Built Different',
      'Available: Black / Charcoal / Bone',
      'Ships in matte black zip poly bag with thank you card',
      'DHF Winter — Drop 001',
    ],
    collection: 'DHF Winter — Drop 001',
  },
  {
    id: 'f_duffle',
    slug: 'duffle-bag',
    name: 'Duffle Bag',
    price: 78,
    img: '/images/f_duffle.png',
    imgLg: '/images/f_duffle.png',
    droppingFirst: false,
    sizes: ['One Size'],
    description: 'The Dog House gym bag. 600 denier polyester canvas, fully lined, with a separate shoe compartment, multiple pockets, and an adjustable padded shoulder strap. Dog House logo on the front.',
    details: [
      '600 denier polyester canvas — 210 denier lining',
      'Separate zippered shoe/wet gear compartment',
      'Front pocket and zippered end pocket',
      'Adjustable padded shoulder strap',
      'DTF logo print on front panel',
      '10.75"H × 20.75"W × 9"D — ~2,008 cubic inches',
      'Dog Days — Drop 001',
    ],
    collection: 'Dog Days — Drop 001',
  },
]

export const GOLF_PRODUCTS: Product[] = [
  {
    id: 'g_cap_navy',
    slug: 'rope-cap-navy',
    name: 'Rope Cap',
    price: 44,
    img: '/images/g_cap_navy.png',
    imgLg: '/images/g_cap_navy.png',
    droppingFirst: true,
    sizes: ['One Size'],
    description: 'The Dog House Golf rope cap in navy. DHG patch, performance fabric, rope brim detail. Made for the course, worn everywhere.',
    details: [
      'Dog House Golf embroidered patch',
      'Performance polyester shell',
      'Perforated side panels',
      'Navy rope brim detail',
      'Adjustable snapback closure',
      'Dog House Golf — Drop 001',
    ],
    collection: 'Dog House Golf — Drop 001',
  },
  {
    id: 'g_cap_charcoal',
    slug: 'charcoal-rope-cap',
    name: 'Charcoal Rope Cap',
    price: 44,
    img: '/images/g_cap_charcoal.png',
    imgLg: '/images/g_cap_charcoal.png',
    droppingFirst: true,
    sizes: ['One Size'],
    description: 'The Dog House Golf rope cap in charcoal. Same build, different colorway. Versatile enough for 18 holes or beyond.',
    details: [
      'Dog House Golf embroidered patch',
      'Performance polyester shell',
      'Perforated side panels',
      'Charcoal rope brim detail',
      'Adjustable snapback closure',
      'Dog House Golf — Drop 001',
    ],
    collection: 'Dog House Golf — Drop 001',
  },
  {
    id: 'g_bucket',
    slug: 'bucket-hat',
    name: 'Bucket Hat',
    price: 44,
    img: '/images/g_bucket.png',
    imgLg: '/images/g_bucket.png',
    droppingFirst: true,
    sizes: ['One Size'],
    description: 'Navy cotton bucket hat with embroidered "Dog House Golf" wordmark on the front. Clean, minimal, and made for the back nine.',
    details: [
      'Cotton canvas construction',
      'Embroidered Dog House Golf wordmark',
      'Classic bucket silhouette',
      'Dog House Golf — Drop 001',
    ],
    collection: 'Dog House Golf — Drop 001',
  },
  {
    id: 'g_polo',
    slug: 'striped-polo',
    name: 'Striped Polo',
    price: 68,
    img: '/images/g_polo.png',
    imgLg: '/images/g_polo.png',
    droppingFirst: false,
    sizes: ['L', 'XL'],
    description: 'Performance striped polo with DHG embroidered patch on the left chest. "DHG" woven collar label. Moisture-wicking fabric built for the course.',
    details: [
      'Performance moisture-wicking fabric',
      'Fine stripe pattern',
      'DHG embroidered patch — left chest',
      'DHG woven collar label',
      '3-button placket',
      'Dog House Golf — Drop 001',
    ],
    collection: 'Dog House Golf — Drop 001',
  },
  {
    id: 'g_qzip',
    slug: 'quarter-zip',
    name: 'Quarter Zip',
    price: 118,
    img: '/images/g_qzip2.png',
    imgLg: '/images/g_qzip2.png',
    droppingFirst: false,
    sizes: ['L', 'XL'],
    description: 'Performance quarter zip in white stripe. DHG embroidered patch on the left chest, woven DHG collar label. Layering piece built for early tee times.',
    details: [
      'Performance stretch fabric',
      'Fine stripe pattern',
      'DHG embroidered patch — left chest',
      'DHG woven collar label',
      'Quarter zip with pull',
      'Dog House Golf — Drop 001',
    ],
    collection: 'Dog House Golf — Drop 001',
  },
  {
    id: 'g_vest',
    slug: 'performance-vest',
    name: 'Performance Vest',
    price: 90,
    img: '/images/g_vest.png',
    imgLg: '/images/g_vest.png',
    droppingFirst: false,
    sizes: ['L', 'XL'],
    description: 'Navy performance vest with DHG embroidered patch on the left chest and "DHG" woven collar label. Full zip, clean silhouette, made for layering on the course.',
    details: [
      'Soft-shell performance fabric',
      'DHG embroidered patch — left chest',
      'DHG woven collar label',
      'Full zip — side pockets',
      'Dog House Golf — Drop 001',
    ],
    collection: 'Dog House Golf — Drop 001',
  },
  {
    id: 'g_belt',
    slug: 'needlepoint-belt',
    name: 'Needlepoint Belt',
    price: 68,
    img: '/images/g_belt.png',
    imgLg: '/images/g_belt.png',
    droppingFirst: false,
    sizes: ['One Size'],
    description: 'Navy needlepoint belt with the Dog House Golf golden retriever, crossed clubs, and golf balls stitched in. Brass buckle, brown leather trim. The most Dog House thing you can wear on the course.',
    details: [
      'Hand-stitched needlepoint canvas',
      'Navy background — Dog House Golf motif',
      'Brass buckle — brown leather trim',
      'Adjustable fit',
      'Dog House Golf — Drop 001',
    ],
    collection: 'Dog House Golf — Drop 001',
  },
  {
    id: 'g_hoodie',
    slug: 'golf-hoodie',
    name: 'Golf Hoodie',
    price: 85,
    img: '/images/g_hoodie2.png',
    imgLg: '/images/g_hoodie2.png',
    droppingFirst: false,
    sizes: ['L', 'XL'],
    description: 'Navy pullover hoodie with "Dog House Golf" across the chest in white and gold. DHG patch on the sleeve. Built for post-round comfort.',
    details: [
      'Heavyweight fleece construction',
      '"Dog House Golf" chest graphic',
      'DHG patch — sleeve',
      'Kangaroo pocket',
      'Dog House Golf — Drop 001',
    ],
    collection: 'Dog House Golf — Drop 001',
  },
]
